# version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/budget_tracker.db
      - SECRET_KEY=your-production-secret-key-change-this
      - ENVIRONMENT=production
    volumes:
      - backend_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:80" # Map to nginx port 80
    depends_on:
      - backend

volumes:
  backend_data:
